version: '3.1'

services:
  database:
    image: mariadb:10.3
    container_name: maria_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
    volumes:
      - ./docker/mariadb:/docker-entrypoint-initdb.d/
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb/log:/var/log/mysql
    ports:
      - "${DATABASE_PORT}:3306"
    command:
      'mysqld --innodb-flush-method=fsync'
  adminer:
    image: adminer
    restart: always
    ports:
      - 9200:8080
    links:
      - database
    environment:
      ADMINER_DESIGN: "arcs-material"
      ADMINER_DEFAULT_SERVER: "database"
  app:
    container_name: cakeapi
    environment:
      DATABASE_URL: "mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_NAME}?encoding=utf8&timezone=UTC&cacheMetadata=true&quoteIdentifiers=false&persistent=false"
    env_file:
      - .env
    build:
      ./docker
    ports:
      - "9090:80"
    volumes:
      - ./:/var/www/
    links:
      - database
    depends_on:
      - database
    command: ["./wait-for-it.sh", "database:3306"]
